accelerate launch --config_file examples/flux/model_training/full/accelerate_config.yaml examples/flux/model_training/train.py \
  --dataset_base_path dataset/CUHK-Pedes/images \
  --dataset_metadata_path dataset/CUHK-Pedes/pairs_filter.txt \
  --data_file_keys "image,prompt" \
  --max_pixels 1048576 \
  --dataset_repeat 1 \
  --model_id_with_origin_paths "black-forest-labs/FLUX.1-Kontext-dev:flux1-kontext-dev.safetensors,black-forest-labs/FLUX.1-Kontext-dev:text_encoder/model.safetensors,black-forest-labs/FLUX.1-Kontext-dev:text_encoder_2/,black-forest-labs/FLUX.1-Kontext-dev:ae.safetensors" \
  --learning_rate 1e-5 \
  --num_epochs 5 \
  --remove_prefix_in_ckpt "pipe.dit." \
  --output_path "./models/train/FLUX.1_lora_spotlight_1204_t2i" \
  --lora_base_model "dit" \
  --lora_target_modules "a_to_qkv,b_to_qkv,ff_a.0,ff_a.2,ff_b.0,ff_b.2,a_to_out,b_to_out,proj_out,norm.linear,norm1_a.linear,norm1_b.linear,to_qkv_mlp" \
  --lora_rank 32 \
  --align_to_opensource_format \
  --save_steps 1000 \
  --use_gradient_checkpointing  > log/flux_train_1204_t2i.log 2>&1